/* eslint-disable no-unused-vars */
export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AZURE_API_ERROR = 'AZURE_API_ERROR',
  AZURE_CONNECTION_ERROR = 'AZURE_CONNECTION_ERROR',
  AZURE_PIPELINE_FETCH_ERROR = 'AZURE_PIPELINE_FETCH_ERROR',
  AZURE_PIPELINE_RUNS_FETCH_ERROR = 'AZURE_PIPELINE_RUNS_FETCH_ERROR',
  AZURE_PIPELINE_RUN_DETAILS_ERROR = 'AZURE_PIPELINE_RUN_DETAILS_ERROR',
  AZURE_BATCH_PIPELINE_DETAILS_ERROR = 'AZURE_BATCH_PIPELINE_DETAILS_ERROR',
  AZURE_ENVIRONMENT_RUNS_ERROR = 'AZURE_ENVIRONMENT_RUNS_ERROR',
  AZURE_RELEASED_VERSIONS_ERROR = 'AZURE_RELEASED_VERSIONS_ERROR',
}
