#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Store the root directory
ROOT_DIR=$(pwd)

# Run frontend pre-commit hook
echo "Running frontend pre-commit hooks..."
cd "$ROOT_DIR/frontend"
npm run build
npm run test

# Run backend pre-commit hook
echo "Running backend pre-commit hooks..."
cd "$ROOT_DIR/backend"
npm run build
npm run test
