# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ShipIt Api CI/CD

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'
    types: [opened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build Job

    runs-on: ubuntu-latest

    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install root dependencies
        run: npm install --ignore-scripts

      - name: Run husky install explicitly
        run: npx husky install

      - name: Install npm dependencies
        working-directory: backend
        run: |
          npm install

      - name: Build backend project
        working-directory: backend
        run: |
          npm run build

      - name: Prepare lean deploy artifact
        working-directory: backend
        run: |
          rm -rf dist-deploy
          mkdir -p dist-deploy
          cp package*.json dist-deploy/
          cp -r dist dist-deploy/
          npm ci --production --prefix dist-deploy

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/dist-deploy/**

  deploy:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
    name: Deploy Job
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: dist-deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24030E42C0AF42EAB8D29726F17A1C3A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D785376F2DDD42398AC7F87383A1FEC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6279B77E87C8401CAFC5D2C1A0B60B5D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shipit-api'
          package: dist-deploy
